version: '3.9'
services:
  discord_bot:
    build: .
    environment:
      - TOKEN=${TOKEN}
      - CHANNEL_ID_CMD=${CHANNEL_ID_CMD}
      - CHANNEL_ID_BOT=${CHANNEL_ID_BOT}
      - CHANNEL_ID_CHAT=${CHANNEL_ID_CHAT}
      - CHANNEL_ID_MUSIC=${CHANNEL_ID_MUSIC}
    volumes:
      - .:/app
    working_dir: /app
    command: sh -c "python3 bot.py & python3 command.py & python3 chat.py & python3 music.py"
